### ISSUE TITLE
today doesnt update selected date

### ISSUE THREAD

**Issue by khoshrang** [razaghimahdi/Compose-Persian-Date-Picker#3]
hi,
in date picker dialog the today buttons doesn't change the selected date

**Comment by razaghimahdi** [comment]
Hi there,
please check out the new version and if it's ok or not just let me know😀🤗

**Comment by khoshrang** [comment]
thanks for your fast response the today button still doesn't call onDateChanged

**Comment by razaghimahdi** [comment]
can u please specifically share me ur code?

**Comment by khoshrang** [comment]
yes, as you can see i have a Log in onDateChanged , but its not being fired on today button clock

imagine datePicker starts with today date, I change it to tomorrow till here its ok it has tomorrows date, but when I click on today button the dialog shows today's date but the Log is not fired to set the variable again

```

           PersianDatePickerDialog(
                rememberPersianDatePicker,
                Modifier.fillMaxWidth(),
                onDismissRequest = { detailState.showDialogDate = false },
                onDateChanged = { year, month, day ->

                    Log.e("onDateChanged","$year $month $day")

                    val gSelectedDate = LocalDate.of(
                        rememberPersianDatePicker.getGregorianYear(),
                        rememberPersianDatePicker.getGregorianMonth(),
                        rememberPersianDatePicker.getGregorianDay()
                    )

                    detailState.selectedDate = gSelectedDate

                })
```

**Comment by razaghimahdi** [comment]
tnx again, pls check out new version and let me know if it's ok

**Comment by khoshrang** [comment]
Its fixed now
thank you for your great effort in this project, keep up the good work !

**Comment by razaghimahdi** [comment]
> Its fixed now thank you for your great effort in this project, keep up the good work !

good to hear, please give a start. tnx 😀❤
