### ISSUE TITLE
content colors 

### ISSUE THREAD

**Issue by khoshrang** [razaghimahdi/Compose-Persian-Date-Picker#4]
hi again,
           the back ground color can be modified but content colors (texts) wont change by applying new color to contentColor 
           
            PersianDatePickerDialog(
                backgroundColor = MaterialTheme.colorScheme.background,
                contentColor = MaterialTheme.colorScheme.onBackground,
                controller = rememberPersianDatePicker,
                modifier = Modifier.fillMaxWidth(),
                dismissTitle = "اوکی",

                onDismissRequest = { detailState.showDialogDate = false },
                onDateChanged = { year, month, day ->
                })

**Comment by razaghimahdi** [comment]
Hi there, please check out the new version and let me know if it's fixed

**Comment by razaghimahdi** [comment]
I consider that the issue is solved, please let me know if it's not.
