### ISSUE TITLE
updateYearRange

### ISSUE THREAD

**Issue by iceboy1369** [razaghimahdi/Compose-Persian-Date-Picker#6]
تنظیمات مربوط به رنج اعمال نمیشه. سورس خودتونو دانلود و اجرا کردم بدون تغییر. محدوده رو روی
rememberPersianDialogDatePicker.updateMaxYear(1420)
 rememberPersianDialogDatePicker.updateMinYear(1395)
 rememberPersianDialogDatePicker.updateYearRange(10)
گذاشتید ولی بازم داره بازه زمانی 1393 تا 1413 نمایش میده

**Comment by razaghimahdi** [comment]
سلام مرتضی، لطفا فقط از
```kotlin
rememberPersianDialogDatePicker.updateMaxYear(1420)
rememberPersianDialogDatePicker.updateMinYear(1395)
```
استفاده کن، اگر باز هم به این مشکل برخوردی اعلام کن ممنون

**Comment by iceboy1369** [comment]
سلام
در کلاس PersianDatePickerController شما مقدار yearRange رو فقط برای پیشفرض _minYear اضافه کردین برای همین وقتی که update میکنیم تاثیری نداره
private var _minYear: MutableState<Int> = mutableIntStateOf(getPersianYear() - yearRange)
internal val minYear get() = _minYear.value

private var _maxYear: MutableState<Int> = mutableIntStateOf(getPersianYear() + yearRange)
internal val maxYear get() = _maxYear.value

فکر میکنم باید داخل تابع updateYearRange این دو خط رو باید اضافه کنید.

fun updateYearRange(value: Int) {
        _yearRange.value = value
        updateMinYear(getPersianYear() - yearRange)
        updateMaxYear(getPersianYear() + yearRange)
 }
 
 با اجازه تون من پروژه شما رو fork کردم و این تغییرات اعمال کردم و مشکلم برطرف شد.
 بسیار ممنون که این کمپوننت رو ساختید خیلی کمک کرد به من در پروژه شخصیم

**Comment by razaghimahdi** [comment]
سلام دمت گرم، لطفا مرج کن اینجا هم نسخه بذارم خیلی ممنون

**Comment by razaghimahdi** [comment]
فورک که کردی، پول ریکویست بزن، من بقیشو درست میکنم
